/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import config.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author manny
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTitle("Electric Bill System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        registerBtn = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        forgotpass = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(244, 246, 249));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logor.png"))); // NOI18N
        jLabel1.setText("  PowerPay");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 900, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Username");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        UserField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        UserField.setPreferredSize(new java.awt.Dimension(350, 40));
        bg.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        registerBtn.setBackground(new java.awt.Color(46, 134, 222));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(46, 134, 222));
        registerBtn.setText("Register");
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
        });
        bg.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, -1));

        loginbtn.setBackground(new java.awt.Color(46, 134, 222));
        loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.setBorder(null);
        loginbtn.setPreferredSize(new java.awt.Dimension(350, 40));
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        bg.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        forgotpass.setBackground(new java.awt.Color(46, 134, 222));
        forgotpass.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        forgotpass.setForeground(new java.awt.Color(46, 134, 222));
        forgotpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotpass.setText("Forgot Password");
        forgotpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpassMouseClicked(evt);
            }
        });
        bg.add(forgotpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 190, -1));

        PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        PasswordField.setPreferredSize(new java.awt.Dimension(350, 40));
        bg.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login to Your Account");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 900, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Don't have an account?");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
       new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerBtnMouseClicked

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        String username = UserField.getText().trim();
        String password = new String(PasswordField.getPassword()).trim();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both username and password.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        connectDB db = new connectDB();
        try {
            int userId = 0;
            // Escape single quotes in username to prevent SQL errors
            String safeUsername = username.replace("'", "''");
            // Hash the password before checking
            String hashedPassword = config.connectDB.hashPassword(password);
            String safePassword = hashedPassword.replace("'", "''");
            String sql = "SELECT * FROM users WHERE username = '" + safeUsername + "' AND password = '" + safePassword + "'";
            ResultSet rs = db.getData(sql);

            if (rs.next()) {
                String status = rs.getString("status");
                String role = rs.getString("role");
                username = rs.getString("username");
                userId = rs.getInt("id");
                if (status != null && status.equalsIgnoreCase("Pending")) {
                    JOptionPane.showMessageDialog(this, "Your account is pending approval.", "Login Denied", JOptionPane.WARNING_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Login successful!", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    config.usersession session = config.usersession.getInstance();
                    session.setId(userId);
                    session.setUsername(username);
                    session.setFirstname(rs.getString("firstname"));
                    session.setLastname(rs.getString("lastname"));
                    session.setEmail(rs.getString("email"));
                    session.setAddress(rs.getString("address"));
                    session.setStatus(rs.getString("status"));
                    session.setRole(role);
                    session.setImage(rs.getString("image"));
                    session.setAccNum(rs.getString("account_number")); // Set account number in session
                    session.setLoggedIn(true);
                    
                    if (role.equalsIgnoreCase("user")) {
                        new user.UserDashboard(session).setVisible(true);
                        admin.ActionLogger.logAction(userId, "User logged in");
                    } else if (role.equalsIgnoreCase("admin")) {
                        new admin.AdminDashboard().setVisible(true);
                        admin.ActionLogger.logAction(userId, "Admin logged in");
                    } else {
                        JOptionPane.showMessageDialog(this, "Unknown user role.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error during login: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void forgotpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassMouseClicked
       new ForgotPassword().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_forgotpassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserField;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel forgotpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel registerBtn;
    // End of variables declaration//GEN-END:variables
}
