/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import config.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author manny
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegisterForm = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        confPassField = new javax.swing.JPasswordField();
        typeField = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        to_register = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(134, 206, 203));
        jPanel1.setLayout(null);

        RegisterForm.setBackground(new java.awt.Color(134, 206, 203));
        RegisterForm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 36), new java.awt.Color(19, 122, 127))); // NOI18N
        RegisterForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RegisterForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameField.setBackground(new java.awt.Color(190, 200, 209));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        RegisterForm.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Full Name :");
        RegisterForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username :");
        RegisterForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, 30));

        usernameField.setBackground(new java.awt.Color(190, 200, 209));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        RegisterForm.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password :");
        RegisterForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, 30));

        emailField.setBackground(new java.awt.Color(190, 200, 209));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        RegisterForm.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, 30));

        passwordField.setBackground(new java.awt.Color(190, 200, 209));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        RegisterForm.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 160, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("User Type :");
        RegisterForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Confirm Password :");
        RegisterForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, 30));

        confPassField.setBackground(new java.awt.Color(190, 200, 209));
        confPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confPassFieldActionPerformed(evt);
            }
        });
        RegisterForm.add(confPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, 30));

        typeField.setBackground(new java.awt.Color(102, 102, 102));
        typeField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        typeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Admin", "User" }));
        RegisterForm.add(typeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 160, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Email :");
        RegisterForm.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, 30));

        registerButton.setBackground(new java.awt.Color(19, 122, 127));
        registerButton.setText("Register");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        RegisterForm.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 120, 30));

        to_register.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        to_register.setForeground(new java.awt.Color(0, 0, 204));
        to_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        to_register.setText("Login");
        to_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                to_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                to_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                to_registerMouseExited(evt);
            }
        });
        RegisterForm.add(to_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 50, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Already have an Account?");
        RegisterForm.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 150, -1));

        jPanel1.add(RegisterForm);
        RegisterForm.setBounds(180, 20, 370, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void confPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confPassFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        String name = nameField.getText().trim();
        String username = usernameField.getText().trim();
        String email = emailField.getText().trim();
        String userType = typeField.getSelectedItem().toString();
        String password = new String(passwordField.getPassword()).trim();
        String confirmPassword = new String(confPassField.getPassword()).trim();
        
        if (name.isEmpty() || username.isEmpty() || email.isEmpty() || userType.equals("Select User Type") || password.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(null, "Invalid email format!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (userType.equals("Select User Type")) {
            JOptionPane.showMessageDialog(null, "Please select a valid role!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (password.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        connectDB con = new connectDB();
        Connection cn = con.getConnection();

        if (cn == null) {
            JOptionPane.showMessageDialog(null, "Database connection failed!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String checkEmailSql = "SELECT COUNT(*) FROM users WHERE email = ?";
        try (PreparedStatement emailPst = cn.prepareStatement(checkEmailSql)) {
            emailPst.setString(1, email);
            try (ResultSet rsEmail = emailPst.executeQuery()) {
                if (rsEmail.next() && rsEmail.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(null, "Email already exists!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String checkUsernameSql = "SELECT COUNT(*) FROM users WHERE username = ?";
        try (PreparedStatement usernamePst = cn.prepareStatement(checkUsernameSql)) {
            usernamePst.setString(1, username);
            try (ResultSet rsUsername = usernamePst.executeQuery()) {
                if (rsUsername.next() && rsUsername.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(null, "Username already exists!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String insertSql = "INSERT INTO users (name, username, email, password, role) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement pst = cn.prepareStatement(insertSql)) {
            pst.setString(1, name);
            pst.setString(2, username);
            pst.setString(3, email);
            pst.setString(4, password); 
            pst.setString(5, userType);
            
            int result = pst.executeUpdate();
            if (result == 1) {
                JOptionPane.showMessageDialog(null, "Registered Successfully!");
                new Login().setVisible(true);
                SwingUtilities.getWindowAncestor(nameField).dispose(); 
            } else {
                JOptionPane.showMessageDialog(null, "Registration failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (cn != null) try {
            cn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_registerButtonMouseClicked

    private void to_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_registerMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_to_registerMouseClicked

    private void to_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_registerMouseEntered

    }//GEN-LAST:event_to_registerMouseEntered

    private void to_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_registerMouseExited

    }//GEN-LAST:event_to_registerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegisterForm;
    private javax.swing.JPasswordField confPassField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel to_register;
    private javax.swing.JComboBox<String> typeField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
