/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import java.sql.Connection;
import java.sql.PreparedStatement;


public class PayBill extends javax.swing.JFrame {

    /**
     * Creates new form PayBill
     */
    public PayBill() {
        initComponents();
    }

    private int billId;

    public void loadBillData(int billId, String accountNumber, String billMonth, int kwhUsed, double amountDue, java.sql.Date dueDate, String status) {
        this.billId = billId;
        accountnumber.setText(accountNumber);
        monthof1.setText(billMonth);
        amountduefield.setText(String.format("%.2f", amountDue));
        enteramountfield.setText("");
        change.setText("");
        methodcombobox.setSelectedIndex(0);
    }

    private void paybillActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String paymentMethod = (String) methodcombobox.getSelectedItem();
        String enteredAmountText = enteramountfield.getText().trim();

        if (paymentMethod == null || paymentMethod.equals("Select Payment Method")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a payment method.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        double amountDue;
        double enteredAmount;
        try {
            amountDue = Double.parseDouble(amountduefield.getText());
            enteredAmount = Double.parseDouble(enteredAmountText);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid amount.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (enteredAmount < amountDue) {
            javax.swing.JOptionPane.showMessageDialog(this, "Entered amount cannot be less than amount due.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        double changeAmount = enteredAmount - amountDue;
        change.setText(String.format("%.2f", changeAmount));

        try {
            Connection conn = config.connectDB.getConnection();
            conn.setAutoCommit(false);

            // Insert payment record
            String insertPaymentQuery = "INSERT INTO tbl_payment (bill_id, amount_paid, payment_date, payment_method) VALUES (?, ?, CURDATE(), ?)";
            PreparedStatement insertPst = conn.prepareStatement(insertPaymentQuery);
            insertPst.setInt(1, billId);
            insertPst.setDouble(2, amountDue);
            insertPst.setString(3, paymentMethod);
            int paymentRows = insertPst.executeUpdate();
            insertPst.close();

            if (paymentRows > 0) {
                // Update bill status
                String updateQuery = "UPDATE tbl_bill SET status = 'Paid' WHERE b_id = ?";
                PreparedStatement updatePst = conn.prepareStatement(updateQuery);
                updatePst.setInt(1, billId);
                int rowsUpdated = updatePst.executeUpdate();
                updatePst.close();

                if (rowsUpdated > 0) {
                    conn.commit();
                    javax.swing.JOptionPane.showMessageDialog(this, "Payment successful. Change: " + String.format("%.2f", changeAmount), "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {
                    conn.rollback();
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to update payment status.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } else {
                conn.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to record payment.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

            conn.setAutoCommit(true);
            conn.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error processing payment: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }                                       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        methodcombobox = new javax.swing.JComboBox<>();
        paybill = new javax.swing.JButton();
        enteramountfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amountduefield = new javax.swing.JTextField();
        accountnumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        monthof1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        change = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pay Bill");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Amount Due");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 170, -1));

        methodcombobox.setBackground(new java.awt.Color(255, 255, 255));
        methodcombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        methodcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Method", "Gcash", "Cash", "Bank" }));
        methodcombobox.setPreferredSize(new java.awt.Dimension(350, 40));
        methodcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodcomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(methodcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 170, 40));

        paybill.setBackground(new java.awt.Color(46, 134, 222));
        paybill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paybill.setForeground(new java.awt.Color(255, 255, 255));
        paybill.setText("Pay");
        paybill.setBorder(null);
        paybill.setPreferredSize(new java.awt.Dimension(350, 40));
        paybill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybillActionPerformed(evt);
            }
        });
        jPanel1.add(paybill, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 310, -1));

        enteramountfield.setBackground(new java.awt.Color(255, 255, 255));
        enteramountfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        enteramountfield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(enteramountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Account Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Payment Method");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 110, -1));

        amountduefield.setBackground(new java.awt.Color(255, 255, 255));
        amountduefield.setToolTipText("");
        amountduefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        amountduefield.setEnabled(false);
        amountduefield.setName(""); // NOI18N
        amountduefield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(amountduefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 170, -1));

        accountnumber.setBackground(new java.awt.Color(255, 255, 255));
        accountnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        accountnumber.setEnabled(false);
        accountnumber.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(accountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Enter Amount");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, -1));

        monthof1.setBackground(new java.awt.Color(255, 255, 255));
        monthof1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        monthof1.setEnabled(false);
        monthof1.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(monthof1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Month");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        change.setBackground(new java.awt.Color(255, 255, 255));
        change.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        change.setEnabled(false);
        change.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Change");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  
    private void methodcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_methodcomboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountnumber;
    private javax.swing.JTextField amountduefield;
    private javax.swing.JTextField change;
    private javax.swing.JTextField enteramountfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> methodcombobox;
    private javax.swing.JTextField monthof1;
    private javax.swing.JButton paybill;
    // End of variables declaration//GEN-END:variables
}
