/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bills;

import admin.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import config.connectDB;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;

public class AddBill extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public AddBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        monthcombobox = new javax.swing.JComboBox<>();
        addbillbtn = new javax.swing.JButton();
        kWh = new javax.swing.JTextField();
        accountnumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        duedate = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Bill");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Due Date (MM/DD/YYYY)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("kWh");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        monthcombobox.setBackground(new java.awt.Color(255, 255, 255));
        monthcombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N);
        monthcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "December" }));
        monthcombobox.setPreferredSize(new java.awt.Dimension(350, 40));
        monthcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthcomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(monthcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, 40));

        addbillbtn.setBackground(new java.awt.Color(46, 134, 222));
        addbillbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N;
        addbillbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbillbtn.setText("Add");
        addbillbtn.setBorder(null);
        addbillbtn.setPreferredSize(new java.awt.Dimension(350, 40));
        addbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbillbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbillbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 310, -1));

        kWh.setBackground(new java.awt.Color(255, 255, 255));
        kWh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        kWh.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(kWh, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 170, -1));

        accountnumber.setBackground(new java.awt.Color(255, 255, 255));
        accountnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        accountnumber.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(accountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N;
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Account Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N;
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Month");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        duedate.setBackground(new java.awt.Color(255, 255, 255));
        duedate.setToolTipText("");
        duedate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        duedate.setName(""); // NOI18N;
        duedate.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }

    private void addbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbillbtnActionPerformed
        // Get input values
        String accountNum = accountnumber.getText().trim();
        String kWhText = kWh.getText().trim();
        String billMonth = (String) monthcombobox.getSelectedItem();
        String dueDateText = duedate.getText().trim();

        // Validate account number
        if (accountNum.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an account number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate kWh used
        double kWhUsed;
        try {
            kWhUsed = Double.parseDouble(kWhText);
            if (kWhUsed < 0) {
                JOptionPane.showMessageDialog(this, "kWh used must be a positive number.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for kWh used.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate bill month
        if (billMonth == null || billMonth.equals("Select Month")) {
            JOptionPane.showMessageDialog(this, "Please select a bill month.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate due date format MM/DD/YYYY
        if (!dueDateText.matches("^\\d{2}/\\d{2}/\\d{4}$")) {
            JOptionPane.showMessageDialog(this, "Please enter due date in MM/DD/YYYY format.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calculate amount due
        double amountDue = kWhUsed * 10.50;

        // Set default status
        String status = "Pending";

        // Database operations
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            conn = connectDB.getConnection();

            // Query to get user_id from account_number
            String getUserIdQuery = "SELECT user_id FROM tbl_user WHERE account_number = ?";
            pst = conn.prepareStatement(getUserIdQuery);
            pst.setString(1, accountNum);
            rs = pst.executeQuery();

            int userId = -1;
            if (rs.next()) {
                userId = rs.getInt("user_id");
            } else {
                JOptionPane.showMessageDialog(this, "Account number not found.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            rs.close();
            pst.close();

            // Convert dueDateText to java.sql.Date
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            java.util.Date parsedDate = sdf.parse(dueDateText);
            java.sql.Date dueDate = new java.sql.Date(parsedDate.getTime());

            // Insert bill query
            String insertQuery = "INSERT INTO tbl_bill (user_id, bill_month, kwh_used, amount_due, due_date, status) VALUES (?, ?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(insertQuery);
            pst.setInt(1, userId);
            pst.setString(2, billMonth);
            pst.setDouble(3, kWhUsed);
            pst.setDouble(4, amountDue);
            pst.setDate(5, dueDate);
            pst.setString(6, status);

            int rowsInserted = pst.executeUpdate();
            if (rowsInserted > 0) {
                String message = String.format("Bill added successfully!\nAccount Number: %s\nkWh Used: %.2f\nAmount Due: %.2f\nMonth: %s\nDue Date: %s\nStatus: %s",
                        accountNum, kWhUsed, amountDue, billMonth, dueDateText, status);
                JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);

                // Clear fields after adding
                accountnumber.setText("");
                kWh.setText("");
                monthcombobox.setSelectedIndex(0);
                duedate.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add bill.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format.", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                // Ignore close errors
            }
        }
    }//GEN-LAST:event_addbillbtnActionPerformed

    private void monthcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthcomboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountnumber;
    private javax.swing.JButton addbillbtn;
    private javax.swing.JTextField duedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kWh;
    private javax.swing.JComboBox<String> monthcombobox;
    // End of variables declaration//GEN-END:variables
}
