/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bills;

import admin.*;
import javax.swing.JOptionPane;


public class EditBill extends javax.swing.JFrame {

    private int userId; // Add this field to store the user ID to update

    /**
     * Creates new form EditUser
     */
    public EditBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rolecombobox = new javax.swing.JComboBox<>();
        lastnamefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        updateuserbtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit User");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        firstnamefield.setBackground(new java.awt.Color(255, 255, 255));
        firstnamefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        firstnamefield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(firstnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 310, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Role");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        rolecombobox.setBackground(new java.awt.Color(255, 255, 255));
        rolecombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rolecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "User", "Admin", " " }));
        rolecombobox.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(rolecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 310, 40));

        lastnamefield.setBackground(new java.awt.Color(255, 255, 255));
        lastnamefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        lastnamefield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(lastnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 310, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        emailfield.setBackground(new java.awt.Color(255, 255, 255));
        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        emailfield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 310, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        updateuserbtn.setBackground(new java.awt.Color(46, 134, 222));
        updateuserbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateuserbtn.setForeground(new java.awt.Color(255, 255, 255));
        updateuserbtn.setText("Update");
        updateuserbtn.setBorder(null);
        updateuserbtn.setPreferredSize(new java.awt.Dimension(350, 40));
        updateuserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateuserbtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateuserbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateuserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateuserbtnActionPerformed
        if (this.userId <= 0) {
            JOptionPane.showMessageDialog(this, "Please select a user from the table before updating.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String firstname = firstnamefield.getText().trim();
        String lastname = lastnamefield.getText().trim();
        String email = emailfield.getText().trim();
        String role = (String) rolecombobox.getSelectedItem();

        if (role.equals("Select Role")) {
            JOptionPane.showMessageDialog(this, "Please select a valid role.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int userId = this.userId;

        String sql = "UPDATE users SET firstname = '" + firstname + "', lastname = '" + lastname + "', email = '" + email + "', role = '" + role + "' WHERE id = " + userId;

        boolean success = config.connectDB.updateDatabase(sql);

        if (success) {
            JOptionPane.showMessageDialog(this, "User updated successfully.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            // Log the successful update action
          int currentUserId = config.usersession.getInstance().getId();
            admin.ActionLogger.logAction(currentUserId, "Updated user with ID " + userId);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update user.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateuserbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JComboBox<String> rolecombobox;
    private javax.swing.JButton updateuserbtn;
    // End of variables declaration//GEN-END:variables
}
